### ISSUE TITLE
Upgrade to 3.5

### ISSUE THREAD

**Issue by Brog33** [flathub/net.sf.VICE#21]
Vice 3.5 was released in December

**Comment by Compyx** [comment]
I think you mean 3.5? We never released a 2.5 :)

**Comment by Brog33** [comment]
Ouch. My bad!

**Comment by Compyx** [comment]
No worries.

I am curious how far you can take the --enable-sandbox. I think our current revision handles that, but there could be normal dialogs in various settings pages.
