### ISSUE TITLE
Patch VICE to use XDG directories

### ISSUE THREAD

**Issue by digitalstreamio** [flathub/net.sf.VICE#3]
Currently, VICE does not respect XDG paths and defaults to write to $HOME/.vice directory. This is less than ideal in the sandbox world. The code should be patched to use XDG instead.

**Comment by Compyx** [comment]
Vice does use XDG paths in a way, we currently have the user configuration files in ~/.config/vice. We had a few complaints of people using this flatpak thing, not being able to save their settings. I would highly suggest you use current trunk when using the Gtk3 UI, the 3.2 tarball is very old, trunk contains a lot of fixes, including where to look for config files, not to mention the Gtk3 UI got updated, a lot.
But I have no idea if flatpak supports checking out a source via subversion.

If you can explain to me how this flatpak stuff works and where it expects its user-writable files to reside, and perhaps other files like the ROMs, keymaps, palettes etc, I can probably update VICE to work with flatpak.

/Compyx

**Comment by TingPing** [comment]
> If you can explain to me how this flatpak stuff works and where it expects its user-writable files to reside, and perhaps other files like the ROMs, keymaps, palettes etc, I can probably update VICE to work with flatpak.

It sets `XDG_CONFIG_HOME`, `XDG_CACHE_HOME`, and `XDG_DATA_HOME` to writable locations. So any XDG compliant application just works.

**Comment by Compyx** [comment]
So, if I would use some getenv() code to check if those vars are set I could then determine where the actual location of vicerc etc is when using flatpak?

**Comment by TingPing** [comment]
> So, if I would use some getenv() code to check if those vars are set I could then determine where the actual location of vicerc etc is when using flatpak?

Yes (but XDG is not Flatpak specific). In example not real code:

```c
const char *config_home = getenv("XDG_CONFIG_HOME"):
if (!config_home || !config_home[0])
  config_home = "~/.config"; // Obviously ~ needs expanded
```

@Compyx While we have your attention could you possibly get these files upstreamed also?

- https://github.com/flathub/net.sf.VICE/blob/master/net.sf.VICE.appdata.xml
- https://github.com/flathub/net.sf.VICE/blob/master/net.sf.VICE.desktop

(Again, not Flatpak specific, these are freedesktop standards)

**Comment by Compyx** [comment]
I know XDG is a freedesktop spec, not a flatpak thing.

Those files appear to be C64-centric, we have 11 emulators, so some adjustments will have to be made.

**Comment by TingPing** [comment]
> Those files appear to be C64-centric, we have 11 emulators, so some adjustments will have to be made.

Sure, if you have multiple entry points you would probably name them `net.sf.VICE.C64`, etc.

**Comment by Compyx** [comment]
I will have a look at the `.desktop` files and making VICE respect XDG env vars. Other than that, we don't get involved in binary distribution in any form, no .deb, .rpm or whatever, we don't have the manpower for that.

I don't have a time frame for when the XDG support will be implemented, I have a lot on my plate. I'll let you know.

**Comment by TingPing** [comment]
> Other than that, we don't get involved in binary distribution in any form, no .deb, .rpm or whatever, we don't have the manpower for that.

No worries, ofc the pitch of Flatpak is that its a do once solution run on many distros ;)
