### ISSUE TITLE
Needs higher resolution icon

### ISSUE THREAD

**Issue by TingPing** [flathub/net.sf.VICE#5]
It looks pretty awful atm: https://flathub.org/apps/details/net.sf.VICE

**Comment by digitalstreamio** [comment]
It's supposed to mimic 8-bit art. ;)

Kidding aside, I will fire up GIMP and get some higher quality icons in place.

Thanks for pointing it out.

**Comment by digitalstreamio** [comment]
New high quality app icon is there now.
